# Generated by Django 6.0.4 on 2026-05-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_host',
        ),
    ]
