# Generated by Django 6.0.4 on 2026-04-30 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_latitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('pickup_time', models.DateTimeField()),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('id_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rides_status', to='ride.ridestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Ride_Event',
            fields=[
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='ride.ride')),
            ],
        ),
    ]
