# Generated by Django 6.0.4 on 2026-05-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
