# Generated by Django 6.0.4 on 2026-05-01 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_ride_pickup__ffcae2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='ride_ride_status__a36879_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['id_rider'], name='ride_ride_id_ride_bc4335_idx'),
        ),
    ]
