# Generated by Django 6.0.4 on 2026-05-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_ride_ride_pickup__ffcae2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
